export const COMPANY = {
  name: "Vizio Marketing",
  siteUrl: "https://viziomarketing.com",
  establishedYear: 2018,
  yearsExperience: "8+",
  establishedLabel: "Established 2018",
  foundedLabel: "Founded 2018",
  sinceYearLabel: "Since 2018",
  heroHeadline: "Helping Public Companies Reach Investors Since 2018",
  yearsCopy: "For more than 8 years, we have worked at the intersection of",
  proofYearsLabel: "8+",
  proofYearsDescription:
    "Years around capital markets, investor relations, and growth campaigns",
  phone: "+1(514)900-0022",
  phoneHref: "tel:+15149000022",
  email: "Info@viziomarketing.com",
  emailHref: "mailto:Info@viziomarketing.com",
  addressLine1: "101-4762 Samson Boulevard",
  addressLine2: "Laval, Quebec H7W 2H7",
  addressCountry: "Canada",
} as const;
